services:
  redis_service:
    networks:
      - my_network
    image: redis:latest
    container_name: redis_service_container
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    ports:
      - "6379:6379"

networks:
  my_network:
    driver: bridge